steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "date" ]
options:
  pool:
    name: 'projects/searce-playground/locations/asia-south1/workerPools/ayush-cb-ansible-test-pool'
  logging: CLOUD_LOGGING_ONLY
